package com.test.utils;

import java.util.HashSet;
import java.util.Iterator;

import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONException;

public class Get2HopRunnable implements Runnable{
	
	private long a;
	private long b;
	private HashSet<Long> idHashSet;
	private boolean fromA;
	private boolean first;
	public JSONArray jsonArray;

	private Iterator<Long> iterator;
	private PathFinder pathFinder;
	
	/*
	 * @param froma means idset is generated by a
	 * */
	public Get2HopRunnable(HashSet<Long> hs,long al,long bl,boolean froma,boolean f,PathFinder p) {
		// TODO Auto-generated constructor stub
		idHashSet = hs;
		iterator = idHashSet.iterator();
		a = al;
		b = bl;
		first = f;
		fromA = froma;
		pathFinder = p;
		jsonArray = new JSONArray();
	}
	
	@Override
	public void run() {
		// TODO Auto-generated method stub
		while (iterator.hasNext()) {
			JSONArray temp2Hop = new JSONArray();
			if(fromA){
				temp2Hop = pathFinder.get2HopPaths(iterator.next(),b,first);
				for(int j = 0;j < temp2Hop.length();j++){
					JSONArray tpArray = new JSONArray();
					tpArray.put(a);
					try {
						tpArray.put(temp2Hop.getJSONArray(j).getLong(0));
						tpArray.put(temp2Hop.getJSONArray(j).getLong(1));
						tpArray.put(temp2Hop.getJSONArray(j).getLong(2));
					} catch (JSONException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					jsonArray.put(tpArray);
				}
			}else{
				temp2Hop = pathFinder.get2HopPaths(a,iterator.next(),first);
				for(int j = 0;j < temp2Hop.length();j++){
					JSONArray tpArray = new JSONArray();
					try {
						tpArray.put(temp2Hop.getJSONArray(j).getLong(0));
						tpArray.put(temp2Hop.getJSONArray(j).getLong(1));
						tpArray.put(temp2Hop.getJSONArray(j).getLong(2));
					} catch (JSONException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					tpArray.put(b);
					jsonArray.put(tpArray);
				}
			}
			
		}
	}
}
